In [13]:
import numpy as np
import random

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr=np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a=np.random.randn(1)
a

array([-1.20111643])

In [16]:
arr=np.random.randn(25)
arr

array([-0.16367937,  1.27074348, -1.03120766, -0.39455971,  0.56339348,
        0.38600827, -0.05554972,  0.73697261, -0.66131881, -2.08234761,
       -0.11115628, -0.08329616, -1.11879082, -0.93620463, -0.20681101,
        0.4372985 , -0.21503943, -0.74639702, -1.11287823, -1.13305361,
       -1.55985673, -1.15954709,  1.72054255,  0.44113946, -0.45059577])

In [25]:
arr=np.linspace(0.01,1,100)
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [26]:
arr=arr.reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [27]:
arr=np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [28]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
mat[3,4]

20

In [47]:
mat1=mat[:3,1:2]
#mat1.reshape(3,1)
mat1

array([[ 2],
       [ 7],
       [12]])

In [43]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [44]:
mat[3,:]

array([16, 17, 18, 19, 20])

In [52]:
mat.sum()


325

In [53]:
mat.std()

7.211102550927978

In [57]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [93]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [94]:
ind=np.random.randint(1,10,5)
ind1=np.unique(ind)
ind1

array([1, 2, 3, 8])

In [97]:
arr[ind1]=arr[ind1]+1

In [98]:
arr

array([ 1,  3,  4,  5,  5,  6,  7,  8, 10, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [107]:
cat=np.random.randint(1,100,256).reshape(4,4,4,4)
cat

array([[[[80, 39, 46, 88],
         [99, 16, 93, 58],
         [37, 34, 67, 85],
         [21, 74, 42, 90]],

        [[15,  2, 56, 86],
         [80, 65, 99, 26],
         [11, 76, 98,  1],
         [44, 35, 81, 85]],

        [[67, 62, 78, 54],
         [15, 29, 16, 36],
         [93, 88, 29, 13],
         [16, 67, 63, 56]],

        [[39, 11,  5, 29],
         [20,  5, 90, 18],
         [66, 89, 48, 83],
         [50, 82, 56, 55]]],


       [[[42, 20, 99, 21],
         [60, 16, 60, 12],
         [53, 68, 81, 97],
         [16, 27, 83, 10]],

        [[91, 23,  5, 31],
         [69, 37, 94, 64],
         [ 1, 73, 42, 89],
         [ 7, 11,  3, 39]],

        [[45,  3, 53, 47],
         [49, 98, 25, 83],
         [ 9, 47, 34, 52],
         [42, 33, 43, 25]],

        [[35, 34, 37, 28],
         [ 6, 40, 63, 65],
         [85, 40, 37, 19],
         [88, 53, 80, 88]]],


       [[[58, 50, 12, 83],
         [27, 43, 67,  6],
         [81, 29, 94,  2],
         [85, 41, 13, 31]],

      

In [108]:
cat[:,3:]

array([[[[39, 11,  5, 29],
         [20,  5, 90, 18],
         [66, 89, 48, 83],
         [50, 82, 56, 55]]],


       [[[35, 34, 37, 28],
         [ 6, 40, 63, 65],
         [85, 40, 37, 19],
         [88, 53, 80, 88]]],


       [[[82, 99, 88, 19],
         [85, 16, 40, 15],
         [56, 81, 16, 32],
         [32,  3, 43, 42]]],


       [[[ 6, 68, 34, 28],
         [19, 40, 33, 82],
         [98, 53, 12,  7],
         [79, 64, 17, 59]]]])

In [112]:
np.sum(cat[:,:,0:,2:3])

3416

In [114]:
cat.sum(axis=(-1,-2))

array([[969, 860, 782, 746],
       [765, 679, 688, 798],
       [722, 642, 919, 749],
       [696, 796, 672, 699]])

In [118]:
cat[0,3,:,:].sum()

746

In [154]:
arr=np.random.randint(0,10,6).reshape(3,2)
arr

array([[6, 8],
       [9, 9],
       [0, 7]])

In [157]:
arr[[0,1],:]=arr[[1,0],:]

In [158]:
arr

array([[9, 9],
       [6, 8],
       [0, 7]])

In [192]:
arr1=np.random.random(10)

In [193]:
arr1

array([0.54892195, 0.806531  , 0.79892262, 0.7193837 , 0.03550646,
       0.53080228, 0.8810497 , 0.90700987, 0.78291168, 0.53370276])

In [194]:
np.cumsum(arr1)

array([0.54892195, 1.35545295, 2.15437557, 2.87375927, 2.90926573,
       3.44006801, 4.32111771, 5.22812758, 6.01103925, 6.54474201])

In [201]:
def aver(a,n):
    result=np.cumsum(a)
    
    print(result[n:])
    print(result[:-n])
    result[n:]=result[n:]-result[:-n]
    return result[n-1:]/n

In [202]:
arr2=aver(arr1,3)
arr2

[2.87375927 2.90926573 3.44006801 4.32111771 5.22812758 6.01103925
 6.54474201]
[0.54892195 1.35545295 2.15437557 2.87375927 2.90926573 3.44006801
 4.32111771]


array([0.71812519, 0.77494577, 0.51793759, 0.42856415, 0.48245281,
       0.77295395, 0.85699042, 0.7412081 ])

In [198]:
(0.90700987+ 0.78291168+ 0.53370276)/3

0.7412081033333333