In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt


In [2]:
data=np.random.choice(80,20)
data

array([30, 79, 42, 65, 71,  2,  0, 26, 48, 70, 45, 74, 79,  1,  9, 28, 42,
       18, 59, 39])

In [3]:
data_mean=2
data_std_dev=2

In [4]:
def cal_likelihood(mean,std,data):
    return (1/np.sqrt(2*3.14*(std**2)))*np.exp(-((data-mean)**2)/(2*(std**2)))

In [5]:
prob_a=[]
for point in data:
    prob_a.append(cal_likelihood(data_mean,data_std_dev,point))
prob_data_a=np.array(prob_a)
prob_data_a
prob_data_b=1-prob_data_a

In [6]:
prob_a=0.5
prob_b=0.5


In [7]:
def cal_prob_b(data1,data2):
    return (data1*prob_b)/((data1*prob_b)+(data2*prob_a))
    

In [8]:
new_b=[]
for iterat in range(len(prob_data_a)):
    
    
    new_b.append(cal_prob_b(prob_data_a[iterat],prob_data_b[iterat]))
new_b=np.array(new_b)
shape_b=new_b.shape
new_a=1-new_b
sum_b=new_b.sum()
sum_a=new_a.sum()
    

In [9]:
    new_b

array([5.48442316e-044, 2.96439388e-323, 2.76117417e-088, 6.84920789e-217,
       6.92606622e-260, 1.99521721e-001, 1.21016041e-001, 1.07346400e-032,
       2.68596110e-116, 1.89574379e-252, 8.38837916e-102, 7.53643416e-283,
       2.96439388e-323, 1.76077301e-001, 4.36451993e-004, 4.00042803e-038,
       2.76117417e-088, 2.52677611e-015, 8.35879587e-178, 9.57959099e-076])

In [10]:
mean_b=[]
for iterat in range(len(new_b)):
    
    mean_b.append((np.sum((new_b[iterat]*data[iterat])))/sum_b)
mean_b=np.array(mean_b)
mean_b

array([3.31017389e-042, 4.71338626e-321, 2.33314479e-086, 8.95678816e-215,
       9.89335485e-258, 8.02821096e-001, 0.00000000e+000, 5.61512504e-031,
       2.59381833e-114, 2.66978495e-250, 7.59432475e-100, 1.12200871e-280,
       4.71338626e-321, 3.54243565e-001, 7.90273808e-003, 2.25352869e-036,
       2.33314479e-086, 9.15035334e-014, 9.92188820e-176, 7.51640498e-074])

In [11]:
std_dev_b=[]
for iterat in range(len(new_b)):
    std_dev_b.append((np.sum(new_b[iterat]*((data[iterat]-mean_b[iterat])**2)))/sum_b)
std_dev_b=np.array(std_dev_b)
std_dev_b

array([9.93052167e-041, 3.72209295e-319, 9.79920810e-085, 5.82191231e-213,
       7.02428195e-256, 5.75316581e-001, 0.00000000e+000, 1.45993251e-029,
       1.24503280e-112, 1.86884946e-248, 3.41744614e-098, 8.30286443e-279,
       3.72209295e-319, 1.47720053e-001, 7.09997910e-002, 6.30988032e-035,
       9.79920810e-085, 1.64706360e-012, 5.85391404e-174, 2.93139794e-072])

In [12]:
mean_a=[]
for iterat in range(len(new_a)):
    
    mean_a.append((np.sum((new_a[iterat]*data[iterat])))/sum_a)
mean_a=np.array(mean_a)
mean_a

array([1.53822895, 4.05066957, 2.15352053, 3.3328294 , 3.64047519,
       0.08208792, 0.        , 1.33313176, 2.46116632, 3.58920089,
       2.30734343, 3.79429808, 4.05066957, 0.04224606, 0.46126728,
       1.43568035, 2.15352053, 0.92293737, 3.0251836 , 1.99969764])

In [13]:
std_dev_a=[]
for iterat in range(len(new_a)):
    std_dev_a.append((np.sum(new_a[iterat]*((data[iterat]-mean_a[iterat])**2)))/shape_b)
std_dev_a=np.array(std_dev_a)
std_dev_a

array([[4.05036206e+01],
       [2.80870107e+02],
       [7.93870963e+01],
       [1.90141997e+02],
       [2.26865279e+02],
       [1.47223434e-01],
       [0.00000000e+00],
       [3.04227194e+01],
       [1.03689269e+02],
       [2.20519712e+02],
       [9.11331463e+01],
       [2.46442029e+02],
       [2.80870107e+02],
       [3.77889103e-02],
       [3.64390674e+00],
       [3.52831539e+01],
       [7.93870963e+01],
       [1.45813034e+01],
       [1.56659004e+02],
       [6.84511187e+01]])

In [14]:
updated_prob_b=new_b.sum()/shape_b
updated_prob_a=1-updated_prob_b

In [15]:
normalized_prob_a=(updated_prob_a+updated_prob_b)/updated_prob_a
normalized_prob_b=(updated_prob_a+updated_prob_b)/updated_prob_b


TypeError: scatter() missing 1 required positional argument: 'y'