In [2]:
import numpy as np
import pandas as pd
import nltk
from scipy.stats import poisson
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
userid=list(range(1,1001))


In [4]:
df=pd.read_pickle('news.pickle')

In [5]:
def random_numbr(mean):
    return np.random.normal(mean,15,1)

mean_list=[60,90,120]
mean=np.random.choice(mean_list)


temp=[]
for item in range(len(df['Article_Id'])):
    temp.append(int(random_numbr(mean)))
   

In [6]:
df['Time Span']=temp
df.head()

Article_Id                                              Title  \
0           0  14 dead after bus falls into canal in Telangan...   
1           1  Pratibha Tiwari molested on busy road   Saath ...   
2           2  US  South Korea begin joint military drill ami...   
3           3  Illegal construction in Bengaluru  Will my hou...   
4           4  Punjab Gau Rakshak Dal chief held for assaulti...   

               Author                       Date  \
0    Devyani Sultania  August 22, 2016 12:34 IST   
1      Suparno Sarkar  August 22, 2016 19:47 IST   
2    Namrata Tripathi  August 22, 2016 18:10 IST   
3  S V Krishnamachari  August 22, 2016 17:39 IST   
4      Pranshu Rathee  August 22, 2016 17:34 IST   

                                             Content  \
0  At least 14 people died and 17 others were inj...   
1  TV actress Pratibha Tiwari  who is best known ...   
2  The United States and South Korea began a join...   
3  The relentless drive by Bengaluru s  Bangalore...   
4  Punjab Gau Raksha Dal chief Satish Kumar and h...   

                                                 URL  \
0  http://www.ibtimes.co.in/14-dead-after-bus-fal...   
1                                                NaN   
2  http://www.ibtimes.co.in/us-south-korea-begin-...   
3  http://www.ibtimes.co.in/illegal-construction-...   
4  http://www.ibtimes.co.in/punjab-gau-rakshak-da...   

                                      processed_data  \
0  14   dead   after   bus   fall   into   canal ...   
1  Pratibha   Tiwari   molested   on   busy   roa...   
2  US   South   Korea   begin   joint   military ...   
3  Illegal   construction   in   Bengaluru   Will...   
4  Punjab   Gau   Rakshak   Dal   chief   held   ...   

                                processed_data_title  \
0  At   least   14   people   died   and   17   o...   
1  TV   actress   Pratibha   Tiwari   who   is   ...   
2  The   United   States   and   South   Korea   ...   
3  The   relentless   drive   by   Bengaluru   s ...   
4  Punjab   Gau   Raksha   Dal   chief   Satish  ...   

                                              vector  Time Span  
0  [0.011264392158998921, 0.5887659309584642, 0.3...         73  
1  [0.012585653781287221, 0.012574610383167524, 0...         65  
2  [0.014675911978424305, 0.9420232124013915, 0.0...         49  
3  [0.0143304497248638, 0.9420714222831654, 0.014...         68  
4  [0.8586701793779298, 0.01670396226435967, 0.01...         40

In [7]:
matrix = [lis for lis in df['vector']]
matrix

[array([0.01126439, 0.58876593, 0.37771673, 0.01113908, 0.01111387]),
 array([0.01258565, 0.01257461, 0.01323974, 0.01258453, 0.94901547]),
 array([0.01467591, 0.94202321, 0.01443926, 0.0142878 , 0.01457381]),
 array([0.01433045, 0.94207142, 0.01466007, 0.0143204 , 0.01461766]),
 array([0.85867018, 0.01670396, 0.01715002, 0.01667092, 0.09080491]),
 array([0.10943303, 0.01821551, 0.40901071, 0.4451569 , 0.01818385]),
 array([0.01258107, 0.01261183, 0.94971913, 0.01255626, 0.01253171]),
 array([0.01674735, 0.93295938, 0.01688062, 0.0167253 , 0.01668735]),
 array([0.14350507, 0.38718497, 0.43266066, 0.01820225, 0.01844704]),
 array([0.01454402, 0.53271299, 0.42415329, 0.01429842, 0.01429128]),
 array([0.01868577, 0.41517725, 0.52958932, 0.01820101, 0.01834665]),
 array([0.01339922, 0.01347016, 0.94621162, 0.01334191, 0.01357708]),
 array([0.29504549, 0.11636591, 0.55997534, 0.01430569, 0.01430757]),
 array([0.02008514, 0.02007218, 0.91981829, 0.02001933, 0.02000506]),
 array([0.24015368, 

In [8]:
from  sklearn.cluster import KMeans

In [9]:
def botone():
    kmean=KMeans(n_clusters=5).fit(matrix)
    label=kmean.labels_
    
    topic_number=10
    itearat=0
    iteration=0
    count=0
    no_of_cluster=5
    copy_labels=label
    div=int(topic_number/no_of_cluster)
    
    reminder=topic_number%no_of_cluster
    iterat=0
    article_id_array=[]
    while iteration<div:
        for cluster in range(no_of_cluster):
            arr=np.where(copy_labels==cluster)[0]
            index=np.random.choice(arr)
            copy_labels[index]=10
            #print("news",'\n',df['Article_Id'][index])
            article_id_array.append(df['Article_Id'][index])

           
            


        iteration=iteration+1

    while iterat<reminder:
        number=np.random.randint(0,5)
        array_1=np.where(copy_labels==number)[0]
        index_1=np.random.choice(array_1)
        copy_labels[index_1]=10
        #print("news",(count+1),'\n',df['Article_Id'][index])
        article_id_array.append(df['Article_Id'][index_1])


        itearat=iterat+1
    return article_id_array


        
        
   
  
       
    
        
       
      
         
        

In [10]:
def rand_number():
    no_of_article=len(df['Article_Id'])
    return np.random.randint(0,no_of_article)


In [11]:

def sigmoid(arg):
    return 1/(1+np.exp(-arg))

In [12]:
content_length=df['Content'].apply(len)
average_time=content_length/5
df['average_time']=average_time

In [13]:


def bottwo(read_article_ids,time_span):
    
    served_article_bot2=[]
    trimmed_doc=df[df['Article_Id'].isin(read_article_ids[0])]
    
    
    article_vector=trimmed_doc['vector']
    article_vector=np.array(article_vector)
   
    article_vector=article_vector.reshape(len(read_article_ids[0]),1)
    
    weight_matrix=[]
    avg_time=trimmed_doc['average_time']
    weight_ratio=sigmoid(time_span[0]/avg_time)
    weight_matrix=np.append(weight_matrix,weight_ratio)
   

    
    transponse_of_weight_matrix=weight_matrix.reshape(1,len(read_article_ids[0]))
    
    #print(transponse_of_weight_matrix)
    user_profile=np.dot(article_vector,transponse_of_weight_matrix).sum()
    
    user_profile=user_profile.reshape(1,5)
    user_profile=user_profile[0]
    vector=list(map(list,(df['vector'])))
    
    cos_sim= cosine_similarity( user_profile.reshape(1,-1),vector)
    sorted_similarity=np.argsort(cos_sim[0],-1)
    top_similarity=sorted_similarity[:10]
    index_list=[]
    for article in top_similarity:
        if article not in read_article_ids[0]:
            index_list.append(article)
            
    
    for j in range(7):
        #print('News','\n',df['Title'][index_list[j]])
        served_article_bot2.append(df['Article_Id'][index_list[j]])
        

    for k in range(3):
        get_number=rand_number()
        while get_number in index_list:
            get_number=rand_number()
        served_article_bot2.append(df['Article_Id'][get_number])
    
        #print('News','\n',df['Title'][get_number])
    return served_article_bot2

In [14]:


def poisson_number():
    click_list=[]
    
    click_list.append(poisson.rvs(mu=2,loc=1,size=4))
    return click_list


In [15]:

def session(arg,users,read_list=[],time_list=[]):
    if arg==1:
        clicklist=[]
        time_spent=[0,0,0,0,0,0,0,0,0,0]
        data=pd.DataFrame(columns=['user_id','session','article served','article rank','clicks','time spent'])
        articlerank=np.arange(1,11)
        sessionlist=np.ones(10)
        articleserve=botone()
        clicks=poisson_number()
        
        for itr in range(1,11):
            if itr in (clicks[0]):
                clicklist.append('yes')
            else:
                clicklist.append('no')
                
                
                
        for i in range(10):
            if i in clicks[0]:
                time_spent[i-1]=(int(df[df['Article_Id']==articleserve[i]]['Time Span']))
            


        data['user_id']=np.zeros(10)+users
        data['session']=sessionlist
        data['article served']=articleserve
        data['article rank']=articlerank
        data['clicks']=clicklist
        data['time spent']=time_spent
        if users==1:
            data.to_csv('frame.csv',index=False)
        else:
            data_read=pd.read_csv('frame.csv')
            big_data=pd.concat([data_read,data],ignore_index=True)  
            big_data.to_csv('frame.csv',index=False)
            
       
        time_list.append(list(data[data['clicks']=='yes']['time spent']))
       
        read_list.append(list(data[data['clicks']=='yes']['article served']))
         
    else:
        time_spent=[0,0,0,0,0,0,0,0,0,0]
        clicklist=[]
        data_read=pd.read_csv('frame.csv')
        data=pd.DataFrame(columns=['user_id','session','article served','article rank','clicks','time spent'])
        
        articlerank=np.arange(1,11)
        sessionlist=np.ones(10)*arg
        articleserve=bottwo(read_list,time_list)
        clicks=poisson_number()
        for itr in range(1,11):
            if itr in (clicks[0]):
                clicklist.append('yes')
            else:
                clicklist.append('no')
                
        
        for i in range(len(time_spent)):
            if i in clicks[0]:
                
                time_spent[i-1]=(int(df[df['Article_Id']==articleserve[i]]['Time Span']))
            

        data['user_id']=np.zeros(10)+users
       
        data['session']=sessionlist
        data['article served']=articleserve
        data['article rank']=articlerank
        data['clicks']=clicklist
        data['time spent']=time_spent
        
        big_data=pd.concat([data_read,data],ignore_index=True) 
        big_data.to_csv('frame.csv',index=False)
        read_list.clear()
        time_list.clear()
        
        time_list.append(list(data[data['clicks']=='yes']['time spent']))
       
        read_list.append(list(data[data['clicks']=='yes']['article served']))


In [16]:

def usersession(no_of_users,no_of_sessions):
    for user in range(1,no_of_users+1):
        for session_no in range(1,no_of_sessions+1):
            
            session(session_no,user)
            
            
           
           
           

In [ ]:
usersession(3000,5)

In [18]:
user_file=pd.read_csv('frame.csv')

In [19]:
user_file









user_id  session  article served  article rank clicks  time spent
0          1.0      1.0            3200             1    yes          54
1          1.0      1.0            4247             2    yes          76
2          1.0      1.0            1209             3     no           0
3          1.0      1.0            3539             4    yes          71
4          1.0      1.0             201             5     no           0
5          1.0      1.0            3484             6     no           0
6          1.0      1.0             255             7     no           0
7          1.0      1.0            2453             8     no           0
8          1.0      1.0            1917             9     no           0
9          1.0      1.0            1601            10     no           0
10         1.0      2.0            1229             1    yes          46
11         1.0      2.0             940             2    yes          60
12         1.0      2.0             874             3    yes          55
13         1.0      2.0             883             4     no           0
14         1.0      2.0             950             5    yes          42
15         1.0      2.0             906             6     no           0
16         1.0      2.0            1206             7     no           0
17         1.0      2.0            2270             8     no           0
18         1.0      2.0            1710             9     no           0
19         1.0      2.0            2537            10     no           0
20         1.0      3.0            3000             1     no           0
21         1.0      3.0            2860             2     no           0
22         1.0      3.0             612             3    yes          63
23         1.0      3.0              30             4    yes          75
24         1.0      3.0            3616             5    yes          74
25         1.0      3.0             458             6     no           0
26         1.0      3.0            3165             7     no           0
27         1.0      3.0            4634             8     no           0
28         1.0      3.0             518             9     no           0
29         1.0      3.0            1964            10     no           0
...        ...      ...             ...           ...    ...         ...
14970    300.0      3.0            3000             1     no           0
14971    300.0      3.0            3616             2    yes          63
14972    300.0      3.0              30             3    yes          74
14973    300.0      3.0             458             4     no           0
14974    300.0      3.0            2981             5     no           0
14975    300.0      3.0            3002             6     no           0
14976    300.0      3.0            4156             7     no           0
14977    300.0      3.0            2044             8     no           0
14978    300.0      3.0            3414             9     no           0
14979    300.0      3.0             305            10     no           0
14980    300.0      4.0            3000             1     no           0
14981    300.0      4.0            3616             2    yes          63
14982    300.0      4.0              30             3     no           0
14983    300.0      4.0             458             4    yes          71
14984    300.0      4.0            2981             5     no           0
14985    300.0      4.0            3002             6     no           0
14986    300.0      4.0            4156             7     no           0
14987    300.0      4.0            1736             8     no           0
14988    300.0      4.0             636             9     no           0
14989    300.0      4.0             841            10     no           0
14990    300.0      5.0            3000             1     no           0
14991    300.0      5.0            3616             2    yes          63
14992    300.0      5.0              30             3     no     