In [12]:
import nltk
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import gensim

C:\Users\Ritu\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [2]:
news_articles=pd.read_csv('news_articles.csv')

In [3]:
final_doc=news_articles.copy()

In [4]:
final_doc.drop(columns=['Author','Date','URL'])

Article_Id                                              Title  \
0              0  14 dead after bus falls into canal in Telangan...   
1              1  Pratibha Tiwari molested on busy road   Saath ...   
2              2  US  South Korea begin joint military drill ami...   
3              3  Illegal construction in Bengaluru  Will my hou...   
4              4  Punjab Gau Rakshak Dal chief held for assaulti...   
5              5  Phillipines drug war  1 800 drug-related death...   
6              6  Infosys shares likely to fall on Tuesday after...   
7              7  Dialogue crucial in finding permanent solution...   
8              8  School bus overturns in Jammu killing 1 and in...   
9              9  Rajasthan  Villagers rescue 50 kids after scho...   
10            10  Karnataka bus accident  8 schoolchildren dead ...   
11            11  Meghalaya accident  At least 30 killed and 8 i...   
12            12  Tamil Nadu  2 students dead  over 40 injured a...   
13            13  Uttarakhand  12 dead as bus falls into a gorge...   
14            14  42 missing in Mahad bridge collapse  Met says ...   
15            15  Mumbai-Goa bridge collapse  Two bodies recover...   
16            16  Mumbai-Goa bridge collapse  Death toll rises t...   
17            17  Mumbai-Goa bridge collapse  What we know so fa...   
18            18  Maharashtra  4 from Pune killed  1 injured in ...   
19            19  Uttar Pradesh  7 children dead after van hits ...   
20            20  Maharashtra  7-month-old baby survives Bhiwand...   
21            21  Madhya Pradesh  5 dead  10 injured in truck-je...   
22            22         26 killed after bus catches fire in Taiwan   
23            23  Jaipur  3 killed  5 injured as MLA s son alleg...   
24            24  Fire Breaks Out At Maharashtra Secretariat Com...   
25            25     18-Year-Old Killed in Mumbai Building Collapse   
26            26  Forensic Report Rules Out Sabotage As Cause Be...   
27            27   Star Trek  actor Anton Yelchin dead in fatal ...   
28            28  Multilingual actress Pranitha escapes road acc...   
29            29  Mumbai-Pune Expressway accident kills 17  inju...   
...          ...                                                ...   
4801        4801  India s rank goes up 12 notches in World Bank ...   
4802        4802  China Spent  147 billion To Halt Stock Market ...   
4803        4803  From Five-and-a-Half-Year Low to Three-Month H...   
4804        4804  Big B Invests in Fire Fighting Equipment Compa...   
4805        4805  Moody s Trims India s Growth Forecast to 7  Th...   
4806        4806      Sensex to Touch 32 200 by December 2015  Citi   
4807        4807  Can Sensex Gain from The Slump in Chinese Stoc...   
4808        4808  Sensex May Fall by Over 2 000 Points in Next 3...   
4809        4809  Gold Prices May See Free Fall on US Fed Rate Hike   
4810        4810     Gold Prices May Plunge to Rs 23 000 in a Month   
4811        4811  Rajesh Exports Buys 100  Stake in World s Larg...   
4812        4812  ASUS Zenfone 2 First Impression  A Well Config...   
4813        4813  Lenovo A7000 vs Asus Zenfone 2  ZE500CL  vs Mo...   
4814        4814  Asus Zenfone 2 Release Date  Features  Price  ...   
4815        4815  Top 10 Tips   Tricks for Gamers to Achieve Pin...   
4816        4816  Did You Know  Moto G  Moto E and Moto X have S...   
4817        4817  Six Essential Security Tips Every Whatsapp Use...   
4818        4818  Top 10 Smartphones and Gadgets Released at MWC...   
4819        4819  MWC 2015  Samsung Galaxy S6 Edge Wins Best New...   
4820        4820   Top Six 3D Printing Discoveries of February 2015   
4821        4821  Mobile World Congress 2015  1st Day Highlights...   
4822        4822  Samsung Galaxy S6 and Galaxy S6 Edge  6 Signif...   
4823        4823  HTC One M9 Plus Leaks Online  Expected Feature...   
4824        4824  Samsung Galaxy S6  S6 Edge Launched in India  ...   
4825        4825  iPhone 6 vs 

In [5]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [6]:
stop_words=set(stopwords.words('english'))
exclude=set(string.punctuation)
wordnet_lemmatizer=WordNetLemmatizer()


In [7]:
def lemma(sentence):
    tokenwords=word_tokenize(sentence)
    stemlist=[]
    for word in tokenwords:
        stemlist.append(wordnet_lemmatizer.lemmatize(word))
        stemlist.append(" ")
    return " ".join(stemlist)

In [8]:
def cleaner(sentence):
    tokenwords=word_tokenize(sentence)
    remove_stopword=[word for word in tokenwords if word not in stop_words]
    remove_punc=[word for word in remove_stopword if word not in exclude]
    return " ".join(remove_punc)

In [9]:
final_doc['processed_data']=final_doc['Title'].apply(cleaner)
final_doc['processed_data']=final_doc['Title'].apply(lemma)
final_doc['processed_data_title']=final_doc['Content'].apply(cleaner)
final_doc['processed_data_title']=final_doc['Content'].apply(lemma)

In [16]:
final_doc.head()

Article_Id                                              Title  \
0           0  14 dead after bus falls into canal in Telangan...   
1           1  Pratibha Tiwari molested on busy road   Saath ...   
2           2  US  South Korea begin joint military drill ami...   
3           3  Illegal construction in Bengaluru  Will my hou...   
4           4  Punjab Gau Rakshak Dal chief held for assaulti...   

               Author                       Date  \
0    Devyani Sultania  August 22, 2016 12:34 IST   
1      Suparno Sarkar  August 22, 2016 19:47 IST   
2    Namrata Tripathi  August 22, 2016 18:10 IST   
3  S V Krishnamachari  August 22, 2016 17:39 IST   
4      Pranshu Rathee  August 22, 2016 17:34 IST   

                                             Content  \
0  At least 14 people died and 17 others were inj...   
1  TV actress Pratibha Tiwari  who is best known ...   
2  The United States and South Korea began a join...   
3  The relentless drive by Bengaluru s  Bangalore...   
4  Punjab Gau Raksha Dal chief Satish Kumar and h...   

                                                 URL  \
0  http://www.ibtimes.co.in/14-dead-after-bus-fal...   
1                                                NaN   
2  http://www.ibtimes.co.in/us-south-korea-begin-...   
3  http://www.ibtimes.co.in/illegal-construction-...   
4  http://www.ibtimes.co.in/punjab-gau-rakshak-da...   

                                      processed_data  \
0  14   dead   after   bus   fall   into   canal ...   
1  Pratibha   Tiwari   molested   on   busy   roa...   
2  US   South   Korea   begin   joint   military ...   
3  Illegal   construction   in   Bengaluru   Will...   
4  Punjab   Gau   Rakshak   Dal   chief   held   ...   

                                processed_data_title  
0  At   least   14   people   died   and   17   o...  
1  TV   actress   Pratibha   Tiwari   who   is   ...  
2  The   United   States   and   South   Korea   ...  
3  The   relentless   drive   by   Bengaluru   s ...  
4  Punjab   Gau   Raksha   Dal   chief   Satish  ...

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
bow_transform=CountVectorizer().fit(final_doc['processed_data_title'])

In [20]:
print(bow_transform)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)


In [21]:
tf=bow_transform.fit_transform(final_doc['processed_data'])

In [22]:
print(len(bow_transform.vocabulary_))

9024


In [23]:
feature_name=bow_transform.get_feature_names()

In [38]:
print(tf.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
from sklearn.decomposition import LatentDirichletAllocation

<1x9024 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [26]:
lda=LatentDirichletAllocation(n_components=5)

In [27]:
x=lda.fit(tf)

C:\Users\Ritu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


In [43]:
print(x)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=10,
             mean_change_tol=0.001, n_components=5, n_jobs=1,
             n_topics=None, perp_tol=0.1, random_state=None,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)


In [48]:
Matrix=lda.transform(tf)

In [49]:
Matrix

array([[0.8472951 , 0.01112906, 0.11932664, 0.01112006, 0.01112913],
       [0.38877754, 0.01286827, 0.01253252, 0.01255437, 0.57326731],
       [0.01434448, 0.0142861 , 0.94266693, 0.01429207, 0.01441041],
       ...,
       [0.01434798, 0.01431807, 0.01430962, 0.94271455, 0.01430977],
       [0.02000063, 0.02014144, 0.02000029, 0.91975986, 0.02009778],
       [0.01432665, 0.16827716, 0.01449492, 0.54777634, 0.25512492]])

In [59]:
from sklearn.cluster import KMeans

In [60]:
kmean=KMeans(n_clusters=5).fit(Matrix)

In [61]:
kmean.labels_

array([1, 0, 3, ..., 2, 2, 2])

In [ ]:
for 

array([[ 0.20407231, 61.92061603,  0.20000434, ...,  0.20103576,
         0.20858478,  0.20004746],
       [ 0.20191265,  0.20056979,  0.20000681, ...,  0.20030711,
         0.21035366,  0.20000598],
       [ 1.45385011,  0.20486134,  0.20149694, ...,  0.20014315,
         0.2017013 ,  0.20049756],
       [ 0.20001524,  7.04505947,  0.20000524, ...,  2.69465546,
         1.46029554,  1.87710892],
       [ 0.20198682,  0.2025082 ,  1.09861757, ...,  0.2001165 ,
         0.20002632,  0.20000536]])

In [50]:
def display_topics(model,features_name,no_top_words):
    for topic_idex,topic in enumerate(model.components_):
        print("Topic",topic_idex)
        print("  ".join([features_name[i]
                      for i in topic.argsort()[: -no_top_words -1:-1]]))
        

In [51]:
topics=display_topics(lda,feature_name,20)

Topic 0
to  in  of  for  is  on  say  from  the  india  over  after  not  isis  by  be  govt  delhi  air  police
Topic 1
khan  and  salman  photos  of  to  in  kapoor  on  video  the  for  with  other  sultan  singh  deepika  at  star  padukone
Topic 2
in  office  box  attack  at  to  shah  collection  indian  rukh  killed  isis  day  us  on  kashmir  year  pakistan  india  film
Topic 3
to  android  with  in  modi  how  india  galaxy  samsung  price  update  install  launch  on  note  new  rom  custom  pm  marshmallow
Topic 4
to  2016  in  india  rio  of  olympics  for  and  2015  report  review  up  world  with  by  the  movie  live  open


In [57]:
type(topics)

NoneType

In [40]:
vectorizer = CountVectorizer()
text2 = ["the puppy"]
vectorizer.fit(text2)
vector = vectorizer.transform(text2)
print(vector.toarray())

[[1 1]]
